version: "3.8"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./faiss_data:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  frontend:
    image: python:3.11
    volumes:
      - ./frontend:/frontend
    ports:
      - "8501:8501"
    working_dir: /frontend
    command: bash -c "pip install -r ../backend/requirements.txt && streamlit run streamlit_app.py --server.port=8501 --server.enableCORS false"
    depends_on:
      - backend
